### ISSUE TITLE
Places (MVP 3)

### ISSUE THREAD

**Issue by Mesona** [Mesona/Places#4]
# Places

## Functionality:
- [x] Create Place
- [x] Show Place
- [x] Navigate to show page from index
- [x] Edit Place (Only privacy for now, title edit will be integrated into the Page component)
- [x] Delete Owned Place

## Style
- [x] Places populate '/' in a grid
- [x] '/' can filter between Owned and Unowned Places
- [x] PlacesIndexItem displays bottom menu correctly
- [x] PlacesIndex displays the placeholder Place

**Comment by ronilbhatia** [comment]
This is looking really great so far! I have no comments at this time - Pages is going to be the crux of this project so let me know if you need any help or want to talk through anything in regards to your implementation. 

Keep up the good work!
